"""Add user id to order table

Revision ID: 60fe938fdacb
Revises: c765df09316a
Create Date: 2024-04-28 12:53:15.084524

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "60fe938fdacb"
down_revision: str | None = "c765df09316a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order", sa.Column("user_id", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order", "user_id")
    # ### end Alembic commands ###
